url: https://covidseverity.com/
baseurl: ""

# Site Settings
title: COVID19 Severity Prediction
description: "Forecasting short-term COVID19 severity in the US"
keywords: "COVID19"

markdown: kramdown
exclude: ["LICENSE", "readme.md", "eda"]